//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazadMarket.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazadMarket.Resourses.layout", typeof(layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attract, engage and convert more qualified Auction E-shoppers.
        /// </summary>
        public static string aboutUsDescription {
            get {
                return ResourceManager.GetString("aboutUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALsham Private Universiy.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right-none pull-right company_info.
        /// </summary>
        public static string addressMenuClass {
            get {
                return ResourceManager.GetString("addressMenuClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Auction.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Approved.
        /// </summary>
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to List.
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number.
        /// </summary>
        public static string bankAccountNumber {
            get {
                return ResourceManager.GetString("bankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string books {
            get {
                return ResourceManager.GetString("books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string buildings {
            get {
                return ResourceManager.GetString("buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Expiration Date.
        /// </summary>
        public static string cardExpirationDate {
            get {
                return ResourceManager.GetString("cardExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string cars {
            get {
                return ResourceManager.GetString("cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Product Details.
        /// </summary>
        public static string categoryProductDetails {
            get {
                return ResourceManager.GetString("categoryProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCV.
        /// </summary>
        public static string cCV {
            get {
                return ResourceManager.GetString("cCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes.
        /// </summary>
        public static string clothes {
            get {
                return ResourceManager.GetString("clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Microsoft Way.
        /// </summary>
        public static string contactL1 {
            get {
                return ResourceManager.GetString("contactL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmond, WA 98052-6399.
        /// </summary>
        public static string contactL2 {
            get {
                return ResourceManager.GetString("contactL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;abbr title=&quot;Phone&quot;&gt;P:&lt;/abbr&gt;
        ///    425.555.0100.
        /// </summary>
        public static string contactL3 {
            get {
                return ResourceManager.GetString("contactL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string copyRight {
            get {
                return ResourceManager.GetString("copyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string createNew {
            get {
                return ResourceManager.GetString("createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Board.
        /// </summary>
        public static string dashBoard {
            get {
                return ResourceManager.GetString("dashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Of Add.
        /// </summary>
        public static string dataOfAdd {
            get {
                return ResourceManager.GetString("dataOfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Add.
        /// </summary>
        public static string dateOfAdd {
            get {
                return ResourceManager.GetString("dateOfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Approve.
        /// </summary>
        public static string dateOfApprove {
            get {
                return ResourceManager.GetString("dateOfApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Auction End.
        /// </summary>
        public static string dateOfAuctionEnd {
            get {
                return ResourceManager.GetString("dateOfAuctionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Auction Start.
        /// </summary>
        public static string dateOfAuctionStart {
            get {
                return ResourceManager.GetString("dateOfAuctionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Raise.
        /// </summary>
        public static string dateOfRaise {
            get {
                return ResourceManager.GetString("dateOfRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Rise.
        /// </summary>
        public static string dateOfRise {
            get {
                return ResourceManager.GetString("dateOfRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Sell.
        /// </summary>
        public static string dateOfSell {
            get {
                return ResourceManager.GetString("dateOfSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string deleteMessage {
            get {
                return ResourceManager.GetString("deleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Value.
        /// </summary>
        public static string depositValue {
            get {
                return ResourceManager.GetString("depositValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrioics.
        /// </summary>
        public static string electrioics {
            get {
                return ResourceManager.GetString("electrioics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods.
        /// </summary>
        public static string foods {
            get {
                return ResourceManager.GetString("foods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name Owner.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Added Product.
        /// </summary>
        public static string lastAddedProduct {
            get {
                return ResourceManager.GetString("lastAddedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last of our Product.
        /// </summary>
        public static string lastOfOurProduct {
            get {
                return ResourceManager.GetString("lastOfOurProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sold Product.
        /// </summary>
        public static string lastSoldProduct {
            get {
                return ResourceManager.GetString("lastSoldProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Price.
        /// </summary>
        public static string limitPrice {
            get {
                return ResourceManager.GetString("limitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string localaccount {
            get {
                return ResourceManager.GetString("localaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left-none.
        /// </summary>
        public static string loginMenuClass {
            get {
                return ResourceManager.GetString("loginMenuClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string market {
            get {
                return ResourceManager.GetString("market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string marketing {
            get {
                return ResourceManager.GetString("marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing@mohamed.com.
        /// </summary>
        public static string marketingMail {
            get {
                return ResourceManager.GetString("marketingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Price :.
        /// </summary>
        public static string maxPrice {
            get {
                return ResourceManager.GetString("maxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Raise.
        /// </summary>
        public static string minimumRaise {
            get {
                return ResourceManager.GetString("minimumRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Raise.
        /// </summary>
        public static string minRaise {
            get {
                return ResourceManager.GetString("minRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MISSION IS SIMPLE.
        /// </summary>
        public static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عندما ينقر الزائر على رابط صفحة “من نحن” فهو يمنحك فرصة الحديث معه لبضع ثوانٍ، لذلك ينبغي أن يكون حديثك مثيرا للاهتمام، وملفتا، تخيل أنك في اجتماع مع أحد العملاء لتقنعه بشراء المنتجات أو الخدمات التي تقدمها شركتك في وقت محدود، لتتمكن وبأفضل الطرق من:.
        /// </summary>
        public static string missionP1 {
            get {
                return ResourceManager.GetString("missionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحديث عما يميزك عن غيرك ولِم أنت فريد من نوعك.
        ///إعلام الجمهور بجميع الأنشطة المتعلقة بنشاطك التجاري.
        ///الإجابة على الأسئلة التي يطرحونها، إجابة تلبي احتياجاتهم.
        ///استعراض لمحات عن فريق عملك ومهاراتهم..
        /// </summary>
        public static string missionP2 {
            get {
                return ResourceManager.GetString("missionP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا بد أن تكون الصفحة مُقنعة، بحيثُ تُظهِر لزوار الموقع مدى احترافية شركتك، ما يمنحك فرصة أكبر لتعزيز ثقة العملاء الحاليين، وتحويل الزوار إلى عملاء، وترك انطباع جيّد لدى المستثمرين، فما الذي سيجعل صفحة “من نحن” الخاصة بشركتك، صفحة رائعة ومثالية؟.
        /// </summary>
        public static string missionP3 {
            get {
                return ResourceManager.GetString("missionP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nav navbar-nav pull-right.
        /// </summary>
        public static string navBarMenuClass {
            get {
                return ResourceManager.GetString("navBarMenuClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +963 938 967 624.
        /// </summary>
        public static string phoneNumner {
            get {
                return ResourceManager.GetString("phoneNumner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Price.
        /// </summary>
        public static string primaryPrice {
            get {
                return ResourceManager.GetString("primaryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Auction.
        /// </summary>
        public static string productAuction {
            get {
                return ResourceManager.GetString("productAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products is The Number One in The Entire Market.
        /// </summary>
        public static string productDescription {
            get {
                return ResourceManager.GetString("productDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The List of The Categorized Product .
        /// </summary>
        public static string productDetailsDescription {
            get {
                return ResourceManager.GetString("productDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductsId {
            get {
                return ResourceManager.GetString("ProductsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Type.
        /// </summary>
        public static string ProductsTypeId {
            get {
                return ResourceManager.GetString("ProductsTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasie.
        /// </summary>
        public static string raise {
            get {
                return ResourceManager.GetString("raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Amount.
        /// </summary>
        public static string raiseAmount {
            get {
                return ResourceManager.GetString("raiseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise List.
        /// </summary>
        public static string raiseList {
            get {
                return ResourceManager.GetString("raiseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string registerNewUser {
            get {
                return ResourceManager.GetString("registerNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise Amount.
        /// </summary>
        public static string riseAmount {
            get {
                return ResourceManager.GetString("riseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Of Product.
        /// </summary>
        public static string sold {
            get {
                return ResourceManager.GetString("sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT WE SPECIALIZE INWHAT WE SPECIALIZE IN.
        /// </summary>
        public static string special {
            get {
                return ResourceManager.GetString("special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support@example.com.
        /// </summary>
        public static string supportMail {
            get {
                return ResourceManager.GetString("supportMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string typeName {
            get {
                return ResourceManager.GetString("typeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Items.
        /// </summary>
        public static string usedItems {
            get {
                return ResourceManager.GetString("usedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string userId {
            get {
                return ResourceManager.GetString("userId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Every Time.
        /// </summary>
        public static string valueUP {
            get {
                return ResourceManager.GetString("valueUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Card.
        /// </summary>
        public static string visaCard {
            get {
                return ResourceManager.GetString("visaCard", resourceCulture);
            }
        }
    }
}
